# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from nvidia.ai4m.body_pose.v1 import body_pose_pb2 as nvidia_dot_ai4m_dot_body__pose_dot_v1_dot_body__pose__pb2

GRPC_GENERATED_VERSION = '1.67.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in nvidia/ai4m/body_pose/v1/body_pose_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class BodyPoseServiceStub(object):
    """The BodyPoseService runs quality-mode 3D Body Pose Estimation on a
    video stream, using caller-supplied per-frame tracked body boxes.

    The client streams the COMPRESSED video file as byte chunks; the SERVER
    decodes it frame by frame (BGR uint8) and feeds each frame to the Triton
    3DBodyPoseEstimation backend.
    The service does NOT run body detection: the caller supplies tracked boxes
    per frame (sent up front as tracked_bboxes).

    Outputs are DELAYED and gated by ready: a ready=true response carries the
    pose for an earlier decoded frame (identified by frame_id). After the video
    ends the server drains the buffered tail and emits a stream_flushed=true
    response.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.EstimateBodyPose = channel.stream_stream(
                '/nvidia.ai4m.body_pose.v1.BodyPoseService/EstimateBodyPose',
                request_serializer=nvidia_dot_ai4m_dot_body__pose_dot_v1_dot_body__pose__pb2.BodyPoseRequest.SerializeToString,
                response_deserializer=nvidia_dot_ai4m_dot_body__pose_dot_v1_dot_body__pose__pb2.BodyPoseResponse.FromString,
                _registered_method=True)


class BodyPoseServiceServicer(object):
    """The BodyPoseService runs quality-mode 3D Body Pose Estimation on a
    video stream, using caller-supplied per-frame tracked body boxes.

    The client streams the COMPRESSED video file as byte chunks; the SERVER
    decodes it frame by frame (BGR uint8) and feeds each frame to the Triton
    3DBodyPoseEstimation backend.
    The service does NOT run body detection: the caller supplies tracked boxes
    per frame (sent up front as tracked_bboxes).

    Outputs are DELAYED and gated by ready: a ready=true response carries the
    pose for an earlier decoded frame (identified by frame_id). After the video
    ends the server drains the buffered tail and emits a stream_flushed=true
    response.
    """

    def EstimateBodyPose(self, request_iterator, context):
        """Bidirectional streaming pose estimation over one video stream.

        Protocol:
        1. Client sends a first request with BodyPoseConfig and the full
        tracked_bboxes annotation (all frames).
        2. Client streams the compressed video file as video_data chunks.
        3. Server decodes frames, runs pose per frame, and streams back
        ready=true responses (delayed, frame-aligned) plus periodic
        keep_alive messages, ending with a stream_flushed=true response.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BodyPoseServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'EstimateBodyPose': grpc.stream_stream_rpc_method_handler(
                    servicer.EstimateBodyPose,
                    request_deserializer=nvidia_dot_ai4m_dot_body__pose_dot_v1_dot_body__pose__pb2.BodyPoseRequest.FromString,
                    response_serializer=nvidia_dot_ai4m_dot_body__pose_dot_v1_dot_body__pose__pb2.BodyPoseResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'nvidia.ai4m.body_pose.v1.BodyPoseService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('nvidia.ai4m.body_pose.v1.BodyPoseService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class BodyPoseService(object):
    """The BodyPoseService runs quality-mode 3D Body Pose Estimation on a
    video stream, using caller-supplied per-frame tracked body boxes.

    The client streams the COMPRESSED video file as byte chunks; the SERVER
    decodes it frame by frame (BGR uint8) and feeds each frame to the Triton
    3DBodyPoseEstimation backend.
    The service does NOT run body detection: the caller supplies tracked boxes
    per frame (sent up front as tracked_bboxes).

    Outputs are DELAYED and gated by ready: a ready=true response carries the
    pose for an earlier decoded frame (identified by frame_id). After the video
    ends the server drains the buffered tail and emits a stream_flushed=true
    response.
    """

    @staticmethod
    def EstimateBodyPose(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/nvidia.ai4m.body_pose.v1.BodyPoseService/EstimateBodyPose',
            nvidia_dot_ai4m_dot_body__pose_dot_v1_dot_body__pose__pb2.BodyPoseRequest.SerializeToString,
            nvidia_dot_ai4m_dot_body__pose_dot_v1_dot_body__pose__pb2.BodyPoseResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
