# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: nvidia/ai4m/syntheticvideodetector/v1/syntheticvideodetector.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'nvidia/ai4m/syntheticvideodetector/v1/syntheticvideodetector.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from nvidia.ai4m.ingest.v1 import presigned_url_pb2 as nvidia_dot_ai4m_dot_ingest_dot_v1_dot_presigned__url__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nBnvidia/ai4m/syntheticvideodetector/v1/syntheticvideodetector.proto\x12%nvidia.ai4m.syntheticvideodetector.v1\x1a\x1bgoogle/protobuf/empty.proto\x1a)nvidia/ai4m/ingest/v1/presigned_url.proto\"\x85\x01\n\x1b\x44\x65tectSyntheticVideoRequest\x12\x19\n\x0fvideo_file_data\x18\x01 \x01(\x0cH\x00\x12<\n\rpresigned_url\x18\x02 \x01(\x0b\x32#.nvidia.ai4m.ingest.v1.PresignedUrlH\x00\x42\r\n\x0bvideo_input\"\xca\x02\n\x1c\x44\x65tectSyntheticVideoResponse\x12J\n\x0cservice_info\x18\x01 \x01(\x0b\x32\x32.nvidia.ai4m.syntheticvideodetector.v1.ServiceInfoH\x00\x12P\n\rframe_results\x18\x02 \x01(\x0b\x32\x37.nvidia.ai4m.syntheticvideodetector.v1.FrameResultBatchH\x00\x12N\n\x0c\x66inal_result\x18\x03 \x01(\x0b\x32\x36.nvidia.ai4m.syntheticvideodetector.v1.DetectionResultH\x00\x12+\n\tkeepalive\x18\x04 \x01(\x0b\x32\x16.google.protobuf.EmptyH\x00\x42\x0f\n\rstream_output\"D\n\x0b\x46rameResult\x12\x10\n\x08\x66rame_id\x18\x01 \x01(\r\x12\r\n\x05logit\x18\x02 \x01(\x02\x12\x14\n\x0ctimestamp_ns\x18\x03 \x01(\x03\"W\n\x10\x46rameResultBatch\x12\x43\n\x07results\x18\x01 \x03(\x0b\x32\x32.nvidia.ai4m.syntheticvideodetector.v1.FrameResult\"Z\n\x0f\x44\x65tectionResult\x12\x12\n\nmean_logit\x18\x01 \x01(\x02\x12\x1d\n\x15synthetic_probability\x18\x02 \x01(\x02\x12\x14\n\x0ctotal_frames\x18\x03 \x01(\r\"M\n\x0bServiceInfo\x12\x13\n\x0bnim_version\x18\x01 \x01(\t\x12\x15\n\rmodel_version\x18\x02 \x01(\t\x12\x12\n\nrequest_id\x18\x03 \x01(\t2\xc7\x01\n\x1dSyntheticVideoDetectorService\x12\xa5\x01\n\x14\x44\x65tectSyntheticVideo\x12\x42.nvidia.ai4m.syntheticvideodetector.v1.DetectSyntheticVideoRequest\x1a\x43.nvidia.ai4m.syntheticvideodetector.v1.DetectSyntheticVideoResponse\"\x00(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'nvidia.ai4m.syntheticvideodetector.v1.syntheticvideodetector_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_DETECTSYNTHETICVIDEOREQUEST']._serialized_start=182
  _globals['_DETECTSYNTHETICVIDEOREQUEST']._serialized_end=315
  _globals['_DETECTSYNTHETICVIDEORESPONSE']._serialized_start=318
  _globals['_DETECTSYNTHETICVIDEORESPONSE']._serialized_end=648
  _globals['_FRAMERESULT']._serialized_start=650
  _globals['_FRAMERESULT']._serialized_end=718
  _globals['_FRAMERESULTBATCH']._serialized_start=720
  _globals['_FRAMERESULTBATCH']._serialized_end=807
  _globals['_DETECTIONRESULT']._serialized_start=809
  _globals['_DETECTIONRESULT']._serialized_end=899
  _globals['_SERVICEINFO']._serialized_start=901
  _globals['_SERVICEINFO']._serialized_end=978
  _globals['_SYNTHETICVIDEODETECTORSERVICE']._serialized_start=981
  _globals['_SYNTHETICVIDEODETECTORSERVICE']._serialized_end=1180
# @@protoc_insertion_point(module_scope)
