# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from nvidia.ai4m.syntheticvideodetector.v1 import syntheticvideodetector_pb2 as nvidia_dot_ai4m_dot_syntheticvideodetector_dot_v1_dot_syntheticvideodetector__pb2

GRPC_GENERATED_VERSION = '1.67.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in nvidia/ai4m/syntheticvideodetector/v1/syntheticvideodetector_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SyntheticVideoDetectorServiceStub(object):
    """SyntheticVideoDetectorService analyzes an input video and returns a
    per-frame synthetic-content score along with an aggregated per-video
    score.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.DetectSyntheticVideo = channel.stream_stream(
                '/nvidia.ai4m.syntheticvideodetector.v1.SyntheticVideoDetectorService/DetectSyntheticVideo',
                request_serializer=nvidia_dot_ai4m_dot_syntheticvideodetector_dot_v1_dot_syntheticvideodetector__pb2.DetectSyntheticVideoRequest.SerializeToString,
                response_deserializer=nvidia_dot_ai4m_dot_syntheticvideodetector_dot_v1_dot_syntheticvideodetector__pb2.DetectSyntheticVideoResponse.FromString,
                _registered_method=True)


class SyntheticVideoDetectorServiceServicer(object):
    """SyntheticVideoDetectorService analyzes an input video and returns a
    per-frame synthetic-content score along with an aggregated per-video
    score.
    """

    def DetectSyntheticVideo(self, request_iterator, context):
        """DetectSyntheticVideo is a bidirectional streaming RPC. The client
        streams one MP4 video file per invocation, either as
        DetectSyntheticVideoRequest chunks (video_file_data) or as a single
        message carrying a pre-signed URL (presigned_url). The server returns a
        stream of DetectSyntheticVideoResponse messages: a one-shot ServiceInfo
        banner first, then FrameResultBatch messages as each inference batch
        completes, and a single DetectionResult carrying the aggregated score.
        Empty keepalive messages may be interleaved during quiet periods.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SyntheticVideoDetectorServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'DetectSyntheticVideo': grpc.stream_stream_rpc_method_handler(
                    servicer.DetectSyntheticVideo,
                    request_deserializer=nvidia_dot_ai4m_dot_syntheticvideodetector_dot_v1_dot_syntheticvideodetector__pb2.DetectSyntheticVideoRequest.FromString,
                    response_serializer=nvidia_dot_ai4m_dot_syntheticvideodetector_dot_v1_dot_syntheticvideodetector__pb2.DetectSyntheticVideoResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'nvidia.ai4m.syntheticvideodetector.v1.SyntheticVideoDetectorService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('nvidia.ai4m.syntheticvideodetector.v1.SyntheticVideoDetectorService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SyntheticVideoDetectorService(object):
    """SyntheticVideoDetectorService analyzes an input video and returns a
    per-frame synthetic-content score along with an aggregated per-video
    score.
    """

    @staticmethod
    def DetectSyntheticVideo(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/nvidia.ai4m.syntheticvideodetector.v1.SyntheticVideoDetectorService/DetectSyntheticVideo',
            nvidia_dot_ai4m_dot_syntheticvideodetector_dot_v1_dot_syntheticvideodetector__pb2.DetectSyntheticVideoRequest.SerializeToString,
            nvidia_dot_ai4m_dot_syntheticvideodetector_dot_v1_dot_syntheticvideodetector__pb2.DetectSyntheticVideoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
