# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: nvidia/ai4m/ingest/v1/presigned_url.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'nvidia/ai4m/ingest/v1/presigned_url.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n)nvidia/ai4m/ingest/v1/presigned_url.proto\x12\x15nvidia.ai4m.ingest.v1\"\x8d\x01\n\x0c\x46ileChecksum\x12\x31\n\x04type\x18\x01 \x01(\x0e\x32#.nvidia.ai4m.ingest.v1.ChecksumType\x12\x11\n\x07md5_hex\x18\x02 \x01(\tH\x00\x12\x14\n\nsha256_hex\x18\x03 \x01(\tH\x00\x12\x14\n\nsha512_hex\x18\x04 \x01(\tH\x00\x42\x0b\n\thex_value\"\x18\n\x16ProviderSpecificParams\"\xe9\x03\n\x0cPresignedUrl\x12\x0b\n\x03url\x18\x01 \x01(\t\x12:\n\x08\x63hecksum\x18\x02 \x01(\x0b\x32#.nvidia.ai4m.ingest.v1.FileChecksumH\x00\x88\x01\x01\x12\x1c\n\x0fverify_checksum\x18\x03 \x01(\x08H\x01\x88\x01\x01\x12*\n\x1d\x65xpected_content_length_bytes\x18\x04 \x01(\x04H\x02\x88\x01\x01\x12\x19\n\x0c\x63ontent_type\x18\x05 \x01(\tH\x03\x88\x01\x01\x12\x1f\n\x12\x65xpires_at_unix_ms\x18\x06 \x01(\x04H\x04\x88\x01\x01\x12=\n\x0curl_provider\x18\x07 \x01(\x0e\x32\".nvidia.ai4m.ingest.v1.UrlProviderH\x05\x88\x01\x01\x12O\n\x18provider_specific_params\x18\x08 \x01(\x0b\x32-.nvidia.ai4m.ingest.v1.ProviderSpecificParamsB\x0b\n\t_checksumB\x12\n\x10_verify_checksumB \n\x1e_expected_content_length_bytesB\x0f\n\r_content_typeB\x15\n\x13_expires_at_unix_msB\x0f\n\r_url_provider*@\n\x0bUrlProvider\x12\x1c\n\x18URL_PROVIDER_UNSPECIFIED\x10\x00\x12\x13\n\x0fURL_PROVIDER_S3\x10\x01*x\n\x0c\x43hecksumType\x12\x1d\n\x19\x43HECKSUM_TYPE_UNSPECIFIED\x10\x00\x12\x15\n\x11\x43HECKSUM_TYPE_MD5\x10\x01\x12\x18\n\x14\x43HECKSUM_TYPE_SHA256\x10\x02\x12\x18\n\x14\x43HECKSUM_TYPE_SHA512\x10\x03\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'nvidia.ai4m.ingest.v1.presigned_url_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_URLPROVIDER']._serialized_start=730
  _globals['_URLPROVIDER']._serialized_end=794
  _globals['_CHECKSUMTYPE']._serialized_start=796
  _globals['_CHECKSUMTYPE']._serialized_end=916
  _globals['_FILECHECKSUM']._serialized_start=69
  _globals['_FILECHECKSUM']._serialized_end=210
  _globals['_PROVIDERSPECIFICPARAMS']._serialized_start=212
  _globals['_PROVIDERSPECIFICPARAMS']._serialized_end=236
  _globals['_PRESIGNEDURL']._serialized_start=239
  _globals['_PRESIGNEDURL']._serialized_end=728
# @@protoc_insertion_point(module_scope)
